### ISSUE TITLE
Change test equality checks

### ISSUE THREAD

**Issue by nickghughes** [apooch68/cs4500A1-part2#10]
Currently you are comparing objects using `==` but it should be using the equals() method.
ie
`CS4500_ASSERT_TRUE(qq->peek() == o)`
becomes
`CS4500_ASSERT_TRUE(qq->peek()->equals(o))`

**Comment by nickghughes** [comment]
or does this work? I'm not sure tbh but I would think not. If it does work feel free to close this

**Comment by apooch68** [comment]
this should work because we are checking if its the exact same instance, not just a different object with the same components

**Comment by apooch68** [comment]
in that case though we would need to change it
