### ISSUE TITLE
Remove queue implementation from queue.h

### ISSUE THREAD

**Issue by andyscho** [apooch68/cs4500A1-part2#4]
It seems like a lot of queue.h is implementation details. I'd recommend deleting all fields and the entire QueueBody class.

From the relevant piazza post from the instructors:

> Q: What if there is already an implementation in the spec? A: Let the spec team know that if they don't remove it, they will lose points. Further, they need to purge it from the history. `git rm` is not nearly enough. Also, please write up this incident as a part of your report.

**Comment by EricXuZh** [comment]
Implementations have been removed
