### ISSUE TITLE
Remove build files

### ISSUE THREAD

**Issue by MHebes** [apooch68/cs4500A1-part2#8]
Please remove any files that are generated as part of the build process and add them to your .gitignore - CMakeCache.txt, CMakeFiles, all the googletest stuff, etc.

Recommend just keeping the CMakeLists.txt/.in and then to build do the following:
```sh
mkdir build && cd build
cmake .. && make
```

**Comment by MHebes** [comment]
Specifically, the following need to be removed and added to your gitignore:
```
CMakeCache.txt
CMakeFiles/
cmake_install.cmake
googletest-download/
googletest-src/
lib/
```

**Comment by EricXuZh** [comment]
Removed
